pipeline:
  build_8:
    image: node:8
    commands:
      - npm --loglevel warn install
      - npm run test
    when:
      event: [push, pull_request]

  build_app:
    image: docker:18.03.1-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t file-vault .
    when:
      event: pull_request

  build_app:
    image: docker:18.03.1-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t file-vault-${DRONE_COMMIT_SHA} .
    when:
      branch: master
      event: push

  image_to_quay:
    image: docker:18.03.1-ce
    secrets:
      - DOCKER_PASSWORD
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag file-vault-$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/file-vault:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/file-vault:$${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push
