---
kind: pipeline
name: default
type: kubernetes

environment: 
  IMAGE_URL: quay.io/ukhomeofficedigital
  IMAGE_REPO: file-vault

steps:
- name: build
  pull: if-not-exists
  image: node:14
  commands:
  - yarn install --frozen-lockfile
  - yarn run test
  when:
    branch: master
    event: [ push, pull_request ]

- name: build_file-vault
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - docker build --no-cache -t $${IMAGE_REPO}:$${DRONE_COMMIT_SHA} .
  when:
    branch: master
    event: [ push, pull_request ]

- name: image_to_quay
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
  - docker tag $${IMAGE_REPO}:$${DRONE_COMMIT_SHA} $${IMAGE_URL}/$${IMAGE_REPO}:$${DRONE_COMMIT_SHA}
  - docker push $${IMAGE_URL}/$${IMAGE_REPO}:$${DRONE_COMMIT_SHA}
  when:
    branch: master
    event: [ push, pull_request ]

## Trivy Security Scannner
- name: scan_packages
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
  resources:
    limits:
      cpu: 1000
      memory: 1024Mi
  environment:
    IMAGE_NAME: file-vault:${DRONE_COMMIT_SHA}
    SEVERITY: MEDIUM,HIGH,CRITICAL
    FAIL_ON_DETECTION: false
    IGNORE_UNFIXED: true
  # ALLOW_CVE_LIST_FILE: hof-services-config/file-vault/trivy-cve-exceptions.txt
  when:
    branch: master
    event: [ push, pull_request, tag ]

# #Trivy for base image 
- name: scan_image_os
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/trivy/client:latest
  resources:
    limits:
      cpu: 1000
      memory: 1024Mi
  environment:
    IMAGE_NAME: 14-alpine@sha256:5c33bc6f021453ae2e393e6e20650a4df0a4737b1882d389f17069dc1933fdc5

    SEVERITY: MEDIUM,HIGH,CRITICAL
    FAIL_ON_DETECTION: false
    IGNORE_UNFIXED: true
    # ALLOW_CVE_LIST_FILE: hof-services-config/file-vault/trivy-cve-exceptions.txt
  when:
    branch: master
    event: [ push, pull_request, tag ]

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

...
